jobs:
 # - name: sample_runShCI
  #  type: runSh
  #  steps:
  #    - IN: sample_prodcipipelines_runCI
       # showBuildStatus: true
  #    - TASK:
    #    - script: ls
  
  - name: oldddcint-runsh
    type: runSh
    steps:
      - IN: sample_prodCiPipelinesRepo
       # showBuildStatus: true
      - IN: ship_oldddcint
      - TASK:
        - script: echo $SHIP_OLDDDCINT_INTEGRATION_USERNAME
        - script: echo $SHIP_OLDDDCINT_INTEGRATION_PASSWORD
        - script: echo $SHIP_OLDDDCINT_INTEGRATION_URL
      #- OUT: test_out_img
 
  - name: newddcint-runsh
    type: runSh
    allowPublicAccess: false
    steps:      
      - IN: sample_prodCiPipelinesRepo
       # showBuildStatus: true
      - IN: ship_newddcint
      - TASK:
        - script: echo $SHIP_NEWDDCINT_INTEGRATION_USERNAME
        - script: echo $SHIP_NEWDDCINT_INTEGRATION_PASSWORD
        - script: echo $SHIP_NEWDDCINT_INTEGRATION_URL
  
  - name: oldddcclu-runsh
    type: runSh
    steps:
      - IN: oldddc_cluster
      - TASK:
        - script: echo $OLDDDC_CLUSTER_INTEGRATION_USERNAME
        - script: echo $OLDDDC_CLUSTER_INTEGRATION_PASSWORD
        - script: echo $OLDDDC_CLUSTER_INTEGRATION_URL
      #- OUT: test_out_img
 
  - name: newddcclu-runsh
    type: runSh
    allowPublicAccess: false
    steps:      
      - IN: newddc_cluster
      - TASK:
        - script: echo $NEWDDC_CLUSTER_INTEGRATION_USERNAME
        - script: echo $NEWDDC_CLUSTER_INTEGRATION_PASSWORD
        - script: echo $NEWDDC_CLUSTER_INTEGRATION_URL
        
  - name: manifest_dep
    type: manifest
    steps:
      - IN: deploy_img       
  
  - name: manifest_dep2
    type: manifest
    steps:
      - IN: deploy_img2
      
  - name: deploy-newddcupgradetoplevel
    type: deploy
    method: upgrade
    workflow: serial
    steps:      
     # - IN: manifest_dep
      - IN: manifest_dep2
      - IN: newddc_cluster
      - IN: ddc_dopts
      - TASK: managed  
    flags: new-ddc
  
  - name: deploy-newddcupgradebottom
    type: deploy
    steps:      
      - IN: manifest_dep2
      - IN: newddc_cluster
      - IN: ddc_dopts
      - TASK: managed 
        deployMethod: upgrade
    flags: new-ddc
    
  - name: deploy-newddcdefault
    type: deploy
    steps:      
      - IN: manifest_dep2
      - IN: newddc_cluster
      - IN: ddc_dopts
      - TASK: managed  
    flags: new-ddc
  
  - name: deploy-oldddcupgradetoplevel
    type: deploy
    method: upgrade
    workflow: serial
    steps:      
   #   - IN: manifest_dep
      - IN: manifest_dep2
      - IN: oldddc_cluster
      - IN: ddc_dopts
      - TASK: managed  
    flags: old-ddc
  
  - name: deploy-oldddcupgradebottom
    type: deploy
    steps:      
      - IN: manifest_dep2
      - IN: oldddc_cluster
      - IN: ddc_dopts
      - TASK: managed 
        deployMethod: upgrade
    flags: old-ddc
    
  - name: deploy-oldddcdefault
    type: deploy
    steps:      
      - IN: manifest_dep2
      - IN: oldddc_cluster
      - IN: ddc_dopts
      - TASK: managed  
    flags: old-ddc
  
  - name: deploy-oldddcbluegreen
    type: deploy
    workflow: parallel
    steps:      
    #  - IN: manifest_dep
      - IN: manifest_dep2
      - IN: oldddc_cluster
      - IN: ddc_dopts
      - TASK: managed  
    flags: old-ddc
  
  - name: deploy-oldddcreplace
    type: deploy
    method: replace
    workflow: parallel
    steps:      
      #- IN: manifest_dep
      - IN: manifest_dep2
      - IN: oldddc_cluster
      - IN: ddc_dopts
      - TASK: managed  
    flags: old-ddc
    
  - name: deploy-newddcbluegreen
    type: deploy
    #workflow: parallel
    steps:      
     # - IN: manifest_dep
      - IN: manifest_dep2
      - IN: newddc_cluster
      - IN: ddc_dopts
      - TASK: managed 
        deployMethod: blueGreen
    flags: new-ddc
  
  - name: deploy-newddcreplace
    type: deploy
    #method: replace
    #workflow: parallel
    steps:      
    #  - IN: manifest_dep
      - IN: manifest_dep2
      - IN: newddc_cluster
      - IN: ddc_dopts
      - TASK: managed 
        deployMethod: replace
    flags: new-ddc
    
