jobs:
  - name: sample_runSh-dcl
    type: runSh
    steps:
      - IN: sample_prodCiPipelinesRepo
      - IN: dcl-key
       # showBuildStatus: true
      - TASK:
        - script: echo $DCLKEY_INTEGRATION_USERNAME
        - script: echo $DCLKEY_INTEGRATION_TOKEN
        - script: echo $DCLKEY_NAME
        - script: echo $DCLKEY_ID
        - script: echo $DCLKEY_OPERATION
        - script: echo $DCLKEY_VERSIONID
        - script: echo $DCLKEY_VERSIONNUMBER
        - script: echo $DCLKEY_TYPE
  

  
  
    
