jobs:
  - name: sample_runSh-dcl
    type: runSh
    steps:
      - IN: sample_prodCiPipelinesRepo
      - IN: dcl-key
      - IN: trigger01
       # showBuildStatus: true
      - TASK:
        - script: echo $DCLKEY_INTEGRATION_USERNAME
        - script: echo $DCLKEY_INTEGRATION_TOKEN
        - script: echo $DCLKEY_NAME
        - script: echo $DCLKEY_ID
        - script: echo $DCLKEY_OPERATION
        - script: echo $DCLKEY_VERSIONID
        - script: echo $DCLKEY_VERSIONNUMBER
        - script: echo $DCLKEY_TYPE
  - name: manifest-dcl
    type: manifest
    steps:
      - IN: deploy_img_ddc
  - name: dcl-int-deploy
    type: deploy
    steps:
      - IN: manifest-dcl
      - IN: dcl-cluster
      - TASK: managed
        deployMethod: upgrade
  - name: deploy-upgradetoplevel-dcl
    type: deploy
    method: upgrade
    workflow: serial
    steps:      
      - IN: manifest-dcl
      - IN: dcl-cluster
      - TASK: managed  
  - name: deploy-bluegreen-dcl
    type: deploy
    #workflow: parallel
    steps:      
      - IN: manifest-dcl
      - IN: dcl-cluster
      - TASK: managed 
        deployMethod: blueGreen
        
  - name: deploy-replace-dcl
    type: deploy
    #method: replace
    #workflow: parallel
    steps:      
      - IN: manifest-dcl
      - IN: dcl-cluster
      - TASK: managed 
        deployMethod: replace     
        
  
  
    
